services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "7000:5000"
    env_file:
      - ./auth_service/.env
    # volumes: 
    #   - ./auth_service/src/:/app:cached
    depends_on:
      - postgres
      - redis

  api_service:
    build: api_service
    ports:
      - "9000:5000"
    env_file:
      - ./api_service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    # volumes: 
    #   - ./api_service/src/:/home/app/api:cached
    restart: on-failure
    depends_on:
      - elastic
      - redis

  # admin_service:
  #   build:
  #     context: admin_service
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./admin_service/.env
  #   volumes:
  #     - ./admin_service/:/usr/app/:cached
  #     - static:/usr/app/config/static
  #   restart: on-failure
  #   depends_on:
  #     - postgres

  # etl:
  #   build:
  #     context: etl_service
  #   env_file:
  #     - ./etl_service/.env
  #   restart: on-failure
  #   depends_on:
  #     - postgres
  #     - elastic

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ='Europe/Moscow'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro    
    restart: on-failure

  elastic:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: on-failure

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/data
    restart: on-failure

  nginx:
    image: nginx:1.19.2
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/app/config/static:ro
    restart: on-failure
    depends_on:
      - auth_service
      - api_service

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped


volumes:
  postgres_data:
  elastic_data:
  redis_data:
  static:
