version: '3'
services:
  auth_app:
    build:
      context: ./auth_service
    env_file:
      - ./auth_service/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
  
  postgres:
    container_name: auth_postgres
    image: postgres:13-alpine
    restart: always
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"


volumes:
  psql_data: