# Generated by Django 3.1 on 2021-03-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210307_2357'),
        ('movies', '0003_auto_20210307_2356'),
    ]

    operations = [
    ]
