# Generated by Django 3.1 on 2021-03-09 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210308_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='personrole',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
