# Generated by Django 3.1 on 2021-03-10 07:47
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20210309_1005'),
    ]

    operations = [
        migrations.RunSQL('CREATE TABLE IF NOT EXISTS movies_filmwork_persons (filmwork_id uuid REFERENCES '
                          'movies_filmwork (id) ON UPDATE CASCADE ON DELETE CASCADE,	'
                          'person_id uuid REFERENCES movies_person (id) ON UPDATE CASCADE) ;'),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
                          'ALTER TABLE movies_personrole DROP COLUMN filmwork_id;'
                          'ALTER TABLE movies_personrole ADD filmwork_id UUID;'
                          'ALTER TABLE movies_personrole DROP COLUMN person_id;'
                          'ALTER TABLE movies_personrole ADD person_id UUID;'),
        migrations.RunSQL('ALTER TABLE movies_filmwork_genres DROP COLUMN filmwork_id;'
                          'ALTER TABLE movies_filmwork_genres ADD filmwork_id UUID;'
                          'ALTER TABLE movies_filmwork_genres DROP COLUMN genre_id;'
                          'ALTER TABLE movies_filmwork_genres ADD genre_id UUID;'),
        migrations.RunSQL('ALTER TABLE movies_filmwork_persons DROP COLUMN filmwork_id;'
                          'ALTER TABLE movies_filmwork_persons ADD filmwork_id UUID;'
                          'ALTER TABLE movies_filmwork_persons DROP COLUMN person_id;'
                          'ALTER TABLE movies_filmwork_persons ADD person_id UUID;')
    ]
