# Generated by Django 3.1 on 2021-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20210313_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='filmwork_type',
            field=models.CharField(choices=[('movie', 'фильм'), ('tv_show', 'шоу'), ('series', 'сериал')], default='фильм', max_length=20, verbose_name='тип'),
        ),
    ]
