# Generated by Django 3.1 on 2021-03-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_filmwork_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'фильм'), ('tv_show', 'шоу'), ('series', 'сериал')], max_length=20, null=True, verbose_name='тип'),
        ),
    ]
