# Generated by Django 3.1 on 2021-03-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_replaced_type_with_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['-title'], name='movies_film_title_fe667c_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['rating', 'title'], name='movies_film_rating_d6bbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date', 'title'], name='movies_film_creatio_62b1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='movies_pers_last_na_601cc4_idx'),
        ),
    ]
