# Generated by Django 3.1 on 2021-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210307_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='роль'),
        ),
    ]
