# Generated by Django 3.1 on 2021-03-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_merge_20210307_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='persons',
        ),
    ]
