# Generated by Django 3.1 on 2021-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_filmwork_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='age_limit',
            field=models.IntegerField(null=True, verbose_name='Возрастной ценз'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'фильм'), ('tv_show', 'шоу'), ('series', 'сериал')], max_length=20, verbose_name='тип'),
        ),
    ]
