# Generated by Django 3.1 on 2021-03-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210309_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personrole',
            old_name='temp_id',
            new_name='id',
        ),
    ]
