# Generated by Django 3.1 on 2021-03-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20210313_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='type',
        ),
    ]
