# Generated by Django 3.1 on 2021-03-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20210313_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
