# Generated by Django 3.1 on 2021-03-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_unique_person_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filmwork',
            name='movies_film_title_fe667c_idx',
        ),
        migrations.RemoveIndex(
            model_name='filmwork',
            name='movies_film_rating_d6bbeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='filmwork',
            name='movies_film_creatio_62b1ce_idx',
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['title'], name='movies_film_title_753e28_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['rating'], name='movies_film_rating_74f6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='movies_film_creatio_bb5ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['filmwork_type'], name='movies_film_filmwor_3fb5de_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='movies_genr_name_850734_idx'),
        ),
    ]
