# Generated by Django 3.1 on 2021-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_added_id_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filmwork',
            name='movies_film_id_dd5b50_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='movies_genr_id_7d5d87_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='movies_pers_id_9d3f96_idx',
        ),
    ]
