# Generated by Django 3.1 on 2021-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20210328_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.CharField(choices=[('actor', 'актер'), ('director', 'режиссер'), ('scriptwriter', 'сценарист')], default='актер', max_length=255, verbose_name='роль'),
            preserve_default=False,
        ),
    ]
