"""renamed field

Revision ID: 2b5fd9f2bc1d
Revises: 99a2ea753598
Create Date: 2021-08-04 11:27:47.925394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b5fd9f2bc1d'
down_revision = '99a2ea753598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active_2fa', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active_2FA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active_2FA', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active_2fa')
    # ### end Alembic commands ###
