"""renamed field

Revision ID: 2b5fd9f2bc1d
Revises: 99a2ea753598
Create Date: 2021-08-04 11:27:47.925394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b5fd9f2bc1d'
down_revision = '99a2ea753598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history_web')
    op.drop_table('login_history_smart')
    op.drop_table('login_history_mobile')
    op.create_unique_constraint(None, 'login_history_master', ['id'])
    op.create_unique_constraint(None, 'login_history_master', ['user_device_type'])
    op.add_column('user', sa.Column('is_active_2fa', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active_2FA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active_2FA', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active_2fa')
    op.drop_constraint(None, 'login_history_master', type_='unique')
    op.drop_constraint(None, 'login_history_master', type_='unique')
    op.create_table('login_history_mobile',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_device_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='login_history_master_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_device_type', name='login_history_mobile_pkey')
    )
    op.create_table('login_history_smart',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_device_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='login_history_master_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_device_type', name='login_history_smart_pkey')
    )
    op.create_table('login_history_web',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_device_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='login_history_master_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_device_type', name='login_history_web_pkey')
    )
    # ### end Alembic commands ###
