"""user_device_type

Revision ID: 30f2a8cacd06
Revises: 7093f8dae0ea
Create Date: 2021-07-31 01:05:26.663546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f2a8cacd06'
down_revision = '7093f8dae0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_history', sa.Column('user_device_type', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_history', 'user_device_type')
    # ### end Alembic commands ###
