"""renamed field is_active_2fa

Revision ID: 7093f8dae0ea
Revises: 5e9e7deb88e0
Create Date: 2021-07-26 11:14:11.724356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093f8dae0ea'
down_revision = '5e9e7deb88e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active_2FA', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active_2FA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_2FA', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active_2FA')
    # ### end Alembic commands ###
