"""history_partitioning

Revision ID: 99a2ea753598
Revises: 30f2a8cacd06
Create Date: 2021-07-31 01:49:40.811952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99a2ea753598'
down_revision = '30f2a8cacd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history_master',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('ip_addr', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_device_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_device_type'),
    sa.UniqueConstraint('id', 'user_device_type'),
    postgresql_partition_by='LIST (user_device_type)'
    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE TABLE IF NOT EXISTS "login_history_smart" PARTITION OF "login_history_master" FOR VALUES IN ('smart');
        CREATE TABLE IF NOT EXISTS "login_history_mobile" PARTITION OF "login_history_master" FOR VALUES IN ('mobile');
        CREATE TABLE IF NOT EXISTS "login_history_web" PARTITION OF "login_history_master" FOR VALUES IN ('web');""")
    op.execute("""
        INSERT INTO login_history_master (id, user_id, user_agent, ip_addr, timestamp, user_device_type)
            SELECT id, user_id, user_agent, ip_addr, timestamp, user_device_type
            FROM login_history;
    """)

    op.drop_table('login_history')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_addr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_device_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='login_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='login_history_pkey'),
    sa.UniqueConstraint('id', name='login_history_id_key')
    )
    # ### end Alembic commands ###

    op.execute("""
            INSERT INTO login_history (id, user_id, user_agent, ip_addr, timestamp, user_device_type)
                SELECT id, user_id, user_agent, ip_addr, timestamp, user_device_type
                FROM login_history_master;
        """)
    op.execute("""
            DROP TABLE IF EXISTS "login_history_smart";
            DROP TABLE IF EXISTS "login_history_mobile";
            DROP TABLE IF  EXISTS "login_history_web";""")

    op.drop_table('login_history_master')
