"""empty message

Revision ID: b92507b4cee8
Revises: 7093f8dae0ea
Create Date: 2021-07-31 00:11:40.763967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92507b4cee8'
down_revision = '7093f8dae0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_email')
    # ### end Alembic commands ###
