"""manytomany_roles

Revision ID: da0181bec3fb
Revises: 17019afe0af4
Create Date: 2021-07-18 21:56:32.928044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da0181bec3fb'
down_revision = '17019afe0af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRole',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('userId', postgresql.UUID(), nullable=True),
    sa.Column('roleId', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'login_history', ['id'])
    op.create_foreign_key(None, 'login_history', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'refresh_token', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'login_history', type_='unique')
    op.drop_table('UserRole')
    # ### end Alembic commands ###
