"""Google user unique constraints

Revision ID: e53223d4190b
Revises: 0d9047d7b945
Create Date: 2021-08-05 09:12:48.667334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53223d4190b'
down_revision = '0d9047d7b945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'google_user', ['id'])
    op.create_unique_constraint(None, 'google_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_user', type_='unique')
    op.drop_constraint(None, 'google_user', type_='unique')
    # ### end Alembic commands ###
